### ISSUE TITLE
Mimetype resolver is not working

### ISSUE THREAD

**Issue by JEreth** [dragermrb/capacitor-plugin-media-capture#10]
Thank you for your work. We evaluated the new version and it works fine so far.

We only noticed that the plugin is not returning the `Mimetype` anymore. Seems to be an issue with `getMimeTypeFromUri`.

**Comment by dragermrb** [comment]
Hi @JEreth 

Can you share result output? (`name`, `path`, `type`, etc)

**Comment by dragermrb** [comment]
This issue was closed because it has been inactive
